[package]
name = "system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.1"
handlebars = "4.2.2"
serde_json = "1.0.79"
itertools = "0.10.2"
